### ISSUE TITLE
Release 2.1.1

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#88]
# Release

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:

- [x] Decide a release version depending on major/minor/patch changes in the CHANGELOG.md.
- [x] Update this issue's title to the new version
- [x] `release-prep` PR:
    - [x] Update the CHANGELOG.md.
        - [x] Add a clean `Unreleased` version.
        - [x] Add the version to the old section.
        - [x] Add the current date to the old version.
        - [x] Write or review the `Deployment Migration Notes` section.
        - [x] Ensure the `Deployment Migration Notes` contains the compatible docker images.
        - [x] Write or review a release summary.
        - [x] Remove empty sections from the patch notes.
    - [x] Merge the `release-prep` PR.
- [x] Wait for the main branch to be green.
- [x] Deploy a version with the "main" and test the deployment.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [x] Create a release in the [Authority Portal EE](https://github.com/sovity/authority-portal-ee) repository.
    - [x] Copy the [Keycloak theme](https://github.com/sovity/authority-portal/tree/main/authority-portal-keycloak) from here to the EE repository.
    - [x] Copy the [realm.json](https://github.com/sovity/authority-portal/blob/main/authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.json) from here to the EE repository.
  - [x] Link this release in the EE changelog.
  - [x] Create a release, re-use the changelog section as EE release description.
  - [x] Re-use the version of this release as the title for the EE release.
- [x] Notify the deployment team, which will send a message to the customer about the new release.
- [x] `release-cleanup` PR:
    - [x] Revisit the changed list of tasks and compare it
      with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/authority-portal/blob/main/.github/ISSUE_TEMPLATE/release.md).
      Apply changes where it makes sense.
    - [x] Merge the `release-cleanup` PR.
